import { IoReceipt } from "@react-icons/all-files/io5/IoReceipt"; 
import { IoGameController } from "@react-icons/all-files/io5/IoGameController"; 
import { IoCart } from "@react-icons/all-files/io5/IoCart"; 
import { IoDesktopSharp } from "@react-icons/all-files/io5/IoDesktopSharp"; 
import { IoCarSportSharp } from "@react-icons/all-files/io5/IoCarSportSharp"; 
import { IoShapes } from "@react-icons/all-files/io5/IoShapes"; 
import { IoWineSharp } from "@react-icons/all-files/io5/IoWineSharp"; 
import { IoArrowForwardOutline } from "@react-icons/all-files/io5/IoArrowForwardOutline"; 
import { IoBook } from "@react-icons/all-files/io5/IoBook"; 
import { IoBoat } from "@react-icons/all-files/io5/IoBoat"; 
import { IoBicycle } from "@react-icons/all-files/io5/IoBicycle"; 
import { IoBeerOutline } from "@react-icons/all-files/io5/IoBeerOutline"; 
import { IoBed } from "@react-icons/all-files/io5/IoBed"; 
import { IoBasketball } from "@react-icons/all-files/io5/IoBasketball"; 
import { IoBarbell } from "@react-icons/all-files/io5/IoBarbell"; 
import { IoBarChart } from "@react-icons/all-files/io5/IoBarChart"; 
import { IoAttachSharp } from "@react-icons/all-files/io5/IoAttachSharp"; 
import { IoAnalyticsOutline } from "@react-icons/all-files/io5/IoAnalyticsOutline"; 
import { IoBag } from "@react-icons/all-files/io5/IoBag"; 
import { IoAmericanFootball } from "@react-icons/all-files/io5/IoAmericanFootball"; 
import { IoAirplane } from "@react-icons/all-files/io5/IoAirplane"; 
import { IoAlarm } from "@react-icons/all-files/io5/IoAlarm"; 
import { IoAccessibility } from "@react-icons/all-files/io5/IoAccessibility"; 
import { IoExtensionPuzzleOutline } from "@react-icons/all-files/io5/IoExtensionPuzzleOutline"; 
import { IoEarthSharp } from "@react-icons/all-files/io5/IoEarthSharp"; 
import { IoEarOutline } from "@react-icons/all-files/io5/IoEarOutline"; 
import { IoDocumentText } from "@react-icons/all-files/io5/IoDocumentText"; 
import { IoDice } from "@react-icons/all-files/io5/IoDice"; 
import { IoCutSharp } from "@react-icons/all-files/io5/IoCutSharp"; 
import { IoConstructOutline } from "@react-icons/all-files/io5/IoConstructOutline"; 
import { IoColorPaletteSharp } from "@react-icons/all-files/io5/IoColorPaletteSharp"; 
import { IoColorFillOutline } from "@react-icons/all-files/io5/IoColorFillOutline"; 
import { IoCodeSlash } from "@react-icons/all-files/io5/IoCodeSlash"; 
import { IoCloudUploadOutline } from "@react-icons/all-files/io5/IoCloudUploadOutline"; 
import { IoChatbubblesOutline } from "@react-icons/all-files/io5/IoChatbubblesOutline"; 
import { IoCardOutline } from "@react-icons/all-files/io5/IoCardOutline"; 
import { IoCarSport } from "@react-icons/all-files/io5/IoCarSport"; 
import { IoCamera } from "@react-icons/all-files/io5/IoCamera"; 
import { IoCallSharp } from "@react-icons/all-files/io5/IoCallSharp"; 
import { IoCalculator } from "@react-icons/all-files/io5/IoCalculator"; 
import { IoCafe } from "@react-icons/all-files/io5/IoCafe"; 
import { IoBusiness } from "@react-icons/all-files/io5/IoBusiness"; 
import { IoBus } from "@react-icons/all-files/io5/IoBus"; 
import { IoBulbOutline } from "@react-icons/all-files/io5/IoBulbOutline"; 
import { IoBrushOutline } from "@react-icons/all-files/io5/IoBrushOutline"; 
import { IoBriefcase } from "@react-icons/all-files/io5/IoBriefcase"; 
import { IoGolfOutline } from "@react-icons/all-files/io5/IoGolfOutline"; 
import { IoFlag } from "@react-icons/all-files/io5/IoFlag"; 
import { IoMedalOutline } from "@react-icons/all-files/io5/IoMedalOutline"; 
import { IoMegaphoneOutline } from "@react-icons/all-files/io5/IoMegaphoneOutline"; 
import { IoMusicalNotes } from "@react-icons/all-files/io5/IoMusicalNotes"; 
import { IoNavigate } from "@react-icons/all-files/io5/IoNavigate"; 
import { IoNewspaperOutline } from "@react-icons/all-files/io5/IoNewspaperOutline"; 
import { IoPawSharp } from "@react-icons/all-files/io5/IoPawSharp"; 
import { IoPhonePortrait } from "@react-icons/all-files/io5/IoPhonePortrait"; 
import { IoPizzaOutline } from "@react-icons/all-files/io5/IoPizzaOutline"; 
import { IoPrintOutline } from "@react-icons/all-files/io5/IoPrintOutline"; 
import { IoRestaurantOutline } from "@react-icons/all-files/io5/IoRestaurantOutline"; 
import { IoRocketOutline } from "@react-icons/all-files/io5/IoRocketOutline"; 
import { IoSchool } from "@react-icons/all-files/io5/IoSchool"; 
import { IoShirtOutline } from "@react-icons/all-files/io5/IoShirtOutline"; 
import { IoTicketOutline } from "@react-icons/all-files/io5/IoTicketOutline"; 
import { IoFingerPrintOutline } from "@react-icons/all-files/io5/IoFingerPrintOutline"; 
import { IoFilmOutline } from "@react-icons/all-files/io5/IoFilmOutline"; 
import { IoFastFoodOutline } from "@react-icons/all-files/io5/IoFastFoodOutline"; 
import { IoKeyOutline } from "@react-icons/all-files/io5/IoKeyOutline"; 
import { IoIceCreamOutline } from "@react-icons/all-files/io5/IoIceCreamOutline"; 
import { IoHourglassOutline } from "@react-icons/all-files/io5/IoHourglassOutline"; 
import { IoHeartHalfSharp } from "@react-icons/all-files/io5/IoHeartHalfSharp"; 
import { IoHeartSharp } from "@react-icons/all-files/io5/IoHeartSharp"; 
import { IoHeadset } from "@react-icons/all-files/io5/IoHeadset"; 
import { IoHammer } from "@react-icons/all-files/io5/IoHammer"; 
import { IoGiftSharp } from "@react-icons/all-files/io5/IoGiftSharp"; 
import { IoFootballSharp } from "@react-icons/all-files/io5/IoFootballSharp"; 
import { IoFlaskSharp } from "@react-icons/all-files/io5/IoFlaskSharp"; 
import { IoFlame } from "@react-icons/all-files/io5/IoFlame"; 
import { IoLibraryOutline } from "@react-icons/all-files/io5/IoLibraryOutline"; 
import { IoCashOutline } from "@react-icons/all-files/io5/IoCashOutline"; 

export default function icons(src, className){
    switch(src){
        case 'IoReceipt': return <IoReceipt className={className}/>;
        case 'IoCashOutline': return <IoCashOutline className={className}/>;
        case 'IoGameController': return <IoGameController className={className}/>;
        case 'IoCart': return <IoCart className={className}/>;
        case 'IoDesktopSharp': return <IoDesktopSharp className={className}/>;
        case 'IoCarSportSharp': return <IoCarSportSharp className={className}/>;
        case 'IoAccessibility': return <IoAccessibility className={className}/>;
        case 'IoArrowForwardOutline': return <IoArrowForwardOutline className={className}/>;
        case 'IoWineSharp': return <IoWineSharp className={className}/>;
        case 'IoAlarm': return <IoAlarm className={className}/>;
        case 'IoAirplane': return <IoAirplane className={className}/>;
        case 'IoAmericanFootball': return <IoAmericanFootball className={className}/>;
        case 'IoBag': return <IoBag className={className}/>;
        case 'IoAnalyticsOutline': return <IoAnalyticsOutline className={className}/>;
        case 'IoAttachSharp': return <IoAttachSharp className={className}/>;
        case 'IoBarChart': return <IoBarChart className={className}/>;
        case 'IoBarbell': return <IoBarbell className={className}/>;
        case 'IoBasketball': return <IoBasketball className={className}/>;
        case 'IoBed': return <IoBed className={className}/>;
        case 'IoBeerOutline': return <IoBeerOutline className={className}/>;
        case 'IoBicycle': return <IoBicycle className={className}/>;
        case 'IoBoat': return <IoBoat className={className}/>;
        case 'IoBook': return <IoBook className={className}/>;
        case 'IoBriefcase': return <IoBriefcase className={className}/>;
        case 'IoBrushOutline': return <IoBrushOutline className={className}/>;
        case 'IoBulbOutline': return <IoBulbOutline className={className}/>;
        case 'IoBus': return <IoBus className={className}/>;
        case 'IoBusiness': return <IoBusiness className={className}/>;
        case 'IoCafe': return <IoCafe className={className}/>;
        case 'IoCalculator': return <IoCalculator className={className}/>;
        case 'IoCallSharp': return <IoCallSharp className={className}/>;
        case 'IoCamera': return <IoCamera className={className}/>;
        case 'IoCarSport': return <IoCarSport className={className}/>;
        case 'IoCardOutline': return <IoCardOutline className={className}/>;
        case 'IoChatbubblesOutline': return <IoChatbubblesOutline className={className}/>;
        case 'IoCloudUploadOutline': return <IoCloudUploadOutline className={className}/>;
        case 'IoCodeSlash': return <IoCodeSlash className={className}/>;
        case 'IoColorFillOutline': return <IoColorFillOutline className={className}/>;
        case 'IoColorPaletteSharp': return <IoColorPaletteSharp className={className}/>;
        case 'IoConstructOutline': return <IoConstructOutline className={className}/>;
        case 'IoCutSharp': return <IoCutSharp className={className}/>;
        case 'IoDice': return <IoDice className={className}/>;
        case 'IoDocumentText': return <IoDocumentText className={className}/>;
        case 'IoEarOutline': return <IoEarOutline className={className}/>;
        case 'IoEarthSharp': return <IoEarthSharp className={className}/>;
        case 'IoExtensionPuzzleOutline': return <IoExtensionPuzzleOutline className={className}/>;
        case 'IoFastFoodOutline': return <IoFastFoodOutline className={className}/>;
        case 'IoFilmOutline': return <IoFilmOutline className={className}/>;
        case 'IoFingerPrintOutline': return <IoFingerPrintOutline className={className}/>;
        case 'IoTicketOutline': return <IoTicketOutline className={className}/>;
        case 'IoShirtOutline': return <IoShirtOutline className={className}/>;
        case 'IoSchool': return <IoSchool className={className}/>;
        case 'IoRocketOutline': return <IoRocketOutline className={className}/>;
        case 'IoRestaurantOutline': return <IoRestaurantOutline className={className}/>;
        case 'IoPrintOutline': return <IoPrintOutline className={className}/>;
        case 'IoPizzaOutline': return <IoPizzaOutline className={className}/>;
        case 'IoPhonePortrait': return <IoPhonePortrait className={className}/>;
        case 'IoPawSharp': return <IoPawSharp className={className}/>;
        case 'IoNewspaperOutline': return <IoNewspaperOutline className={className}/>;
        case 'IoNavigate': return <IoNavigate className={className}/>;
        case 'IoMusicalNotes': return <IoMusicalNotes className={className}/>;
        case 'IoMegaphoneOutline': return <IoMegaphoneOutline className={className}/>;
        case 'IoMedalOutline': return <IoMedalOutline className={className}/>;
        case 'IoFlag': return <IoFlag className={className}/>;
        case 'IoGolfOutline': return <IoGolfOutline className={className}/>;
        case 'IoFlame': return <IoFlame className={className}/>;
        case 'IoFlaskSharp': return <IoFlaskSharp className={className}/>;
        case 'IoFootballSharp': return <IoFootballSharp className={className}/>;
        case 'IoGiftSharp': return <IoGiftSharp className={className}/>;
        case 'IoHammer': return <IoHammer className={className}/>;
        case 'IoHeadset': return <IoHeadset className={className}/>;
        case 'IoHeartSharp': return <IoHeartSharp className={className}/>;
        case 'IoHeartHalfSharp': return <IoHeartHalfSharp className={className}/>;
        case 'IoHourglassOutline': return <IoHourglassOutline className={className}/>;
        case 'IoIceCreamOutline': return <IoIceCreamOutline className={className}/>;
        case 'IoKeyOutline': return <IoKeyOutline className={className}/>;
        case 'IoLibraryOutline': return <IoLibraryOutline className={className}/>;
        case 'IoShapes': return <IoShapes className={className}/>;
        default: return false;
    }
}