import { IoReceipt } from "@react-icons/all-files/io5/IoReceipt"; 
import { IoGameController } from "@react-icons/all-files/io5/IoGameController"; 
import { IoCart } from "@react-icons/all-files/io5/IoCart"; 
import { IoDesktopSharp } from "@react-icons/all-files/io5/IoDesktopSharp"; 
import { IoCarSportSharp } from "@react-icons/all-files/io5/IoCarSportSharp"; 
import { IoShapes } from "@react-icons/all-files/io5/IoShapes"; 
import { IoWineSharp } from "@react-icons/all-files/io5/IoWineSharp"; 
import { IoArrowForwardOutline } from "@react-icons/all-files/io5/IoArrowForwardOutline"; 
import { IoBook } from "@react-icons/all-files/io5/IoBook"; 
import { IoBoat } from "@react-icons/all-files/io5/IoBoat"; 
import { IoBicycle } from "@react-icons/all-files/io5/IoBicycle"; 
import { IoBeerOutline } from "@react-icons/all-files/io5/IoBeerOutline"; 
import { IoBed } from "@react-icons/all-files/io5/IoBed"; 
import { IoBasketball } from "@react-icons/all-files/io5/IoBasketball"; 
import { IoBarbell } from "@react-icons/all-files/io5/IoBarbell"; 
import { IoBarChart } from "@react-icons/all-files/io5/IoBarChart"; 
import { IoAttachSharp } from "@react-icons/all-files/io5/IoAttachSharp"; 
import { IoAnalyticsOutline } from "@react-icons/all-files/io5/IoAnalyticsOutline"; 
import { IoBag } from "@react-icons/all-files/io5/IoBag"; 
import { IoAmericanFootball } from "@react-icons/all-files/io5/IoAmericanFootball"; 
import { IoAirplane } from "@react-icons/all-files/io5/IoAirplane"; 
import { IoAlarm } from "@react-icons/all-files/io5/IoAlarm"; 
import { IoAccessibility } from "@react-icons/all-files/io5/IoAccessibility"; 
import { IoExtensionPuzzleOutline } from "@react-icons/all-files/io5/IoExtensionPuzzleOutline"; 
import { IoEarthSharp } from "@react-icons/all-files/io5/IoEarthSharp"; 
import { IoEarOutline } from "@react-icons/all-files/io5/IoEarOutline"; 
import { IoDocumentText } from "@react-icons/all-files/io5/IoDocumentText"; 
import { IoDice } from "@react-icons/all-files/io5/IoDice"; 
import { IoCutSharp } from "@react-icons/all-files/io5/IoCutSharp"; 
import { IoConstructOutline } from "@react-icons/all-files/io5/IoConstructOutline"; 
import { IoColorPaletteSharp } from "@react-icons/all-files/io5/IoColorPaletteSharp"; 
import { IoColorFillOutline } from "@react-icons/all-files/io5/IoColorFillOutline"; 
import { IoCodeSlash } from "@react-icons/all-files/io5/IoCodeSlash"; 
import { IoCloudUploadOutline } from "@react-icons/all-files/io5/IoCloudUploadOutline"; 
import { IoChatbubblesOutline } from "@react-icons/all-files/io5/IoChatbubblesOutline"; 
import { IoCardOutline } from "@react-icons/all-files/io5/IoCardOutline"; 
import { IoCarSport } from "@react-icons/all-files/io5/IoCarSport"; 
import { IoCamera } from "@react-icons/all-files/io5/IoCamera"; 
import { IoCallSharp } from "@react-icons/all-files/io5/IoCallSharp"; 
import { IoCalculator } from "@react-icons/all-files/io5/IoCalculator"; 
import { IoCafe } from "@react-icons/all-files/io5/IoCafe"; 
import { IoBusiness } from "@react-icons/all-files/io5/IoBusiness"; 
import { IoBus } from "@react-icons/all-files/io5/IoBus"; 
import { IoBulbOutline } from "@react-icons/all-files/io5/IoBulbOutline"; 
import { IoBrushOutline } from "@react-icons/all-files/io5/IoBrushOutline"; 
import { IoBriefcase } from "@react-icons/all-files/io5/IoBriefcase"; 
import { IoGolfOutline } from "@react-icons/all-files/io5/IoGolfOutline"; 
import { IoFlag } from "@react-icons/all-files/io5/IoFlag"; 
import { IoMedalOutline } from "@react-icons/all-files/io5/IoMedalOutline"; 
import { IoMegaphoneOutline } from "@react-icons/all-files/io5/IoMegaphoneOutline"; 
import { IoMusicalNotes } from "@react-icons/all-files/io5/IoMusicalNotes"; 
import { IoNavigate } from "@react-icons/all-files/io5/IoNavigate"; 
import { IoNewspaperOutline } from "@react-icons/all-files/io5/IoNewspaperOutline"; 
import { IoPawSharp } from "@react-icons/all-files/io5/IoPawSharp"; 
import { IoPhonePortrait } from "@react-icons/all-files/io5/IoPhonePortrait"; 
import { IoPizzaOutline } from "@react-icons/all-files/io5/IoPizzaOutline"; 
import { IoPrintOutline } from "@react-icons/all-files/io5/IoPrintOutline"; 
import { IoRestaurantOutline } from "@react-icons/all-files/io5/IoRestaurantOutline"; 
import { IoRocketOutline } from "@react-icons/all-files/io5/IoRocketOutline"; 
import { IoSchool } from "@react-icons/all-files/io5/IoSchool"; 
import { IoShirtOutline } from "@react-icons/all-files/io5/IoShirtOutline"; 
import { IoTicketOutline } from "@react-icons/all-files/io5/IoTicketOutline"; 
import { IoFingerPrintOutline } from "@react-icons/all-files/io5/IoFingerPrintOutline"; 
import { IoFilmOutline } from "@react-icons/all-files/io5/IoFilmOutline"; 
import { IoFastFoodOutline } from "@react-icons/all-files/io5/IoFastFoodOutline"; 
import { IoKeyOutline } from "@react-icons/all-files/io5/IoKeyOutline"; 
import { IoIceCreamOutline } from "@react-icons/all-files/io5/IoIceCreamOutline"; 
import { IoHourglassOutline } from "@react-icons/all-files/io5/IoHourglassOutline"; 
import { IoHeartHalfSharp } from "@react-icons/all-files/io5/IoHeartHalfSharp"; 
import { IoHeartSharp } from "@react-icons/all-files/io5/IoHeartSharp"; 
import { IoHeadset } from "@react-icons/all-files/io5/IoHeadset"; 
import { IoHammer } from "@react-icons/all-files/io5/IoHammer"; 
import { IoGiftSharp } from "@react-icons/all-files/io5/IoGiftSharp"; 
import { IoFootballSharp } from "@react-icons/all-files/io5/IoFootballSharp"; 
import { IoFlaskSharp } from "@react-icons/all-files/io5/IoFlaskSharp"; 
import { IoFlame } from "@react-icons/all-files/io5/IoFlame"; 
import { IoLibraryOutline } from "@react-icons/all-files/io5/IoLibraryOutline"; 
import { IoCashOutline } from "@react-icons/all-files/io5/IoCashOutline"; 

export default function icons(src){
    switch(src){
        case 'IoReceipt': return <IoReceipt/>;
        case 'IoCashOutline': return <IoCashOutline/>;
        case 'IoGameController': return <IoGameController/>;
        case 'IoCart': return <IoCart/>;
        case 'IoDesktopSharp': return <IoDesktopSharp/>;
        case 'IoCarSportSharp': return <IoCarSportSharp/>;
        case 'IoAccessibility': return <IoAccessibility/>;
        case 'IoArrowForwardOutline': return <IoArrowForwardOutline/>;
        case 'IoWineSharp': return <IoWineSharp/>;
        case 'IoAlarm': return <IoAlarm/>;
        case 'IoAirplane': return <IoAirplane/>;
        case 'IoAmericanFootball': return <IoAmericanFootball/>;
        case 'IoBag': return <IoBag/>;
        case 'IoAnalyticsOutline': return <IoAnalyticsOutline/>;
        case 'IoAttachSharp': return <IoAttachSharp/>;
        case 'IoBarChart': return <IoBarChart/>;
        case 'IoBarbell': return <IoBarbell/>;
        case 'IoBasketball': return <IoBasketball/>;
        case 'IoBed': return <IoBed/>;
        case 'IoBeerOutline': return <IoBeerOutline/>;
        case 'IoBicycle': return <IoBicycle/>;
        case 'IoBoat': return <IoBoat/>;
        case 'IoBook': return <IoBook/>;
        case 'IoBriefcase': return <IoBriefcase/>;
        case 'IoBrushOutline': return <IoBrushOutline/>;
        case 'IoBulbOutline': return <IoBulbOutline/>;
        case 'IoBus': return <IoBus/>;
        case 'IoBusiness': return <IoBusiness/>;
        case 'IoCafe': return <IoCafe/>;
        case 'IoCalculator': return <IoCalculator/>;
        case 'IoCallSharp': return <IoCallSharp/>;
        case 'IoCamera': return <IoCamera/>;
        case 'IoCarSport': return <IoCarSport/>;
        case 'IoCardOutline': return <IoCardOutline/>;
        case 'IoChatbubblesOutline': return <IoChatbubblesOutline/>;
        case 'IoCloudUploadOutline': return <IoCloudUploadOutline/>;
        case 'IoCodeSlash': return <IoCodeSlash/>;
        case 'IoColorFillOutline': return <IoColorFillOutline/>;
        case 'IoColorPaletteSharp': return <IoColorPaletteSharp/>;
        case 'IoConstructOutline': return <IoConstructOutline/>;
        case 'IoCutSharp': return <IoCutSharp/>;
        case 'IoDice': return <IoDice/>;
        case 'IoDocumentText': return <IoDocumentText/>;
        case 'IoEarOutline': return <IoEarOutline/>;
        case 'IoEarthSharp': return <IoEarthSharp/>;
        case 'IoExtensionPuzzleOutline': return <IoExtensionPuzzleOutline/>;
        case 'IoFastFoodOutline': return <IoFastFoodOutline/>;
        case 'IoFilmOutline': return <IoFilmOutline/>;
        case 'IoFingerPrintOutline': return <IoFingerPrintOutline/>;
        case 'IoTicketOutline': return <IoTicketOutline/>;
        case 'IoShirtOutline': return <IoShirtOutline/>;
        case 'IoSchool': return <IoSchool/>;
        case 'IoRocketOutline': return <IoRocketOutline/>;
        case 'IoRestaurantOutline': return <IoRestaurantOutline/>;
        case 'IoPrintOutline': return <IoPrintOutline/>;
        case 'IoPizzaOutline': return <IoPizzaOutline/>;
        case 'IoPhonePortrait': return <IoPhonePortrait/>;
        case 'IoPawSharp': return <IoPawSharp/>;
        case 'IoNewspaperOutline': return <IoNewspaperOutline/>;
        case 'IoNavigate': return <IoNavigate/>;
        case 'IoMusicalNotes': return <IoMusicalNotes/>;
        case 'IoMegaphoneOutline': return <IoMegaphoneOutline/>;
        case 'IoMedalOutline': return <IoMedalOutline/>;
        case 'IoFlag': return <IoFlag/>;
        case 'IoGolfOutline': return <IoGolfOutline/>;
        case 'IoFlame': return <IoFlame/>;
        case 'IoFlaskSharp': return <IoFlaskSharp/>;
        case 'IoFootballSharp': return <IoFootballSharp/>;
        case 'IoGiftSharp': return <IoGiftSharp/>;
        case 'IoHammer': return <IoHammer/>;
        case 'IoHeadset': return <IoHeadset/>;
        case 'IoHeartSharp': return <IoHeartSharp/>;
        case 'IoHeartHalfSharp': return <IoHeartHalfSharp/>;
        case 'IoHourglassOutline': return <IoHourglassOutline/>;
        case 'IoIceCreamOutline': return <IoIceCreamOutline/>;
        case 'IoKeyOutline': return <IoKeyOutline/>;
        case 'IoLibraryOutline': return <IoLibraryOutline/>;
        case 'IoShapes': return <IoShapes/>;
        default: return false;
    }
}