const mobilStyles = {
    body:{
        position:'fixed',
        padding:0,
        margin:0,
        top:0,
        left:0,
        width: '100%',
        height: '100%',
        display: "flex", 
        flexDirection: "column"},
    input: {
        backgroundColor: "#D7D7D6",
        borderRadius: 5,
        padding: 2,
        fontSize:12,
    },
    label:{
        marginBottom:5,
        fontWeight:'bold',
        fontSize:12,
    },
    buttomMenu:{
        webkitAppearance: 'none',
        width:'100%',
        borderRadius:5, 
        height:27,
        backgroundColor:'#FFFFFF',
        border:0,
        color:'#222222',
        fontWeight:'bold',
        height:40,
        fontSize:12,
    },
    buttomMenuHover:{
        webkitAppearance: 'none',
        width:'100%',
        borderRadius:5, 
        height:27,
        border:0,
        color:'#222222',
        fontWeight:'bold',
        height:40,
        backgroundColor:'#AAAAAA',
        fontSize:12,
    },
    buttomAgregarConsumo:{
        webkitAppearance: 'none',
        marginLeft:20,
        width:130,
        borderRadius:5, 
        height:27,
        backgroundColor:'#3399FF',
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        fontSize:12,
    },
    buttomAgregarConsumoHover:{
        webkitAppearance: 'none',
        marginLeft:20,
        width:130,
        borderRadius:5, 
        height:27,
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        backgroundColor:'#005CB8',
        fontSize:12,
    },
    buttomUpdatePassword:{
        webkitAppearance: 'none',
        marginTop:40,
        width:'100%',
        borderRadius:5, 
        height:27,
        backgroundColor:'#3399FF',
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        fontSize:12,
    },
    buttomUpdatePasswordHover:{
        webkitAppearance: 'none',
        marginTop:40,
        width:'100%',
        borderRadius:5, 
        height:27,
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        backgroundColor:'#005CB8',
        fontSize:12,
    },
    back:{position:'relative', left:210, top:5, backgroundColor:'#FFFFFF', border:0},
    divCenteredItems:{display:'flex', flexDirection:'column',alignItems:'center', width:'100%'},
    formChangePassword:{ display: "flex", flexDirection: 'column', width:'85%'},
    menuContainer:{height: 60,backgroundColor:'#292928',display:'flex' ,justifyContent:'space-between',alignItems:'center',flexDirection: "row"},
    logoHorizontal:{width:250, height:75, marginTop:10},
    configurationButton:{webkitAppearance: 'none',height:25, width:25, paddingRight:40, backgroundColor:'#292928', border:0},
    configurationMenu:{width:150, borderRadius:10,backgroundColor:"#FFFFFF", position:'absolute', right:15, top:75},
    main:{backgroundColor:"#D7D7D6", display:'flex',flexDirection:'column', height:window.innerHeight-60},
    agregarConsumoContainer:{display:'flex',flexDirection:'row', alignItems:'center', margin:20},
    configurationLogo:{width:25, height:25},
    expensesContainer:{ height:'70%',overflow:'auto', width:'100%'},
    expensesTable:{borderSpacing:0, margin: 20, width:window.innerWidth-40},
    expensesRow:{textAlign:"left", height:40},
    expensesValue:{borderBottomStyle:'solid', borderWidth:2},
}

export default mobilStyles;