const webStyles = {
    body:{
        position:'fixed',
        padding:0,
        margin:0,
        top:0,
        left:0,
        width: '100%',
        height: '100%',
        display: "flex", 
        flexDirection: "column"},
    input: {
        backgroundColor: "#D7D7D6",
        borderRadius: 5,
        padding: 3,
    },
    inputEmpty: {
        backgroundColor: "#D7D7D6",
        borderRadius: 5,
        padding: 3,
        borderColor:'red'
    },
    label:{
        marginBottom:5,
        fontWeight:'bold'
    },
    buttomMenu:{
        width:'100%',
        borderRadius:5, 
        height:27,
        backgroundColor:'#FFFFFF',
        border:0,
        color:'#222222',
        fontWeight:'bold',
        height:40,
    },
    buttomMenuHover:{
        width:'100%',
        borderRadius:5, 
        height:27,
        border:0,
        color:'#222222',
        fontWeight:'bold',
        height:40,
        backgroundColor:'#AAAAAA',
    },
    buttomAgregarConsumo:{
        marginLeft:20,
        width:200,
        borderRadius:5, 
        height:27,
        backgroundColor:'#3399FF',
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
    },
    buttomAgregarConsumoHover:{
        marginLeft:20,
        width:200,
        borderRadius:5, 
        height:27,
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        backgroundColor:'#005CB8',
    },
    buttomUpdatePassword:{
        marginTop:40,
        width:'100%',
        borderRadius:5, 
        height:27,
        backgroundColor:'#3399FF',
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
    },
    buttomUpdatePasswordHover:{
        marginTop:40,
        width:'100%',
        borderRadius:5, 
        height:27,
        border:0,
        color:'#FFFFFF',
        fontWeight:'bold',
        backgroundColor:'#005CB8',
    },
    menuContainer:{height: 70,backgroundColor:'#292928',display:'flex' ,justifyContent:'space-between',alignItems:'center',flexDirection: "row"},
    logoHorizontal:{width:250, height:75, marginTop:10},
    configurationButton:{height:25, width:25, marginRight:20, backgroundColor:'#292928', border:0},
    configurationMenu:{width:150, borderRadius:10,backgroundColor:"#FFFFFF", position:'absolute', right:15, top:60},
    main:{backgroundColor:"#D7D7D6", display:'flex',flexDirection:'column', height:window.innerHeight-70},
    agregarConsumoContainer:{display:'flex',flexDirection:'row', margin:20},
    configurationLogo:{width:25, height:25},
    expensesContainer:{ height:'80%',overflow:'auto', width:300},
    expensesTable:{borderSpacing:0, margin: 20, width:250},
    expensesRow:{textAlign:"left", height:40},
    expensesValue:{borderBottomStyle:'solid', borderWidth:2},
    invalidCredentials:{color:'red', fontSize:14, margin:0, fontWeight:'bold'},
}

export default webStyles;