# Generated by Django 3.2.4 on 2021-09-04 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0002_auto_20210903_0250'),
    ]

    operations = [
        migrations.CreateModel(
            name='securityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_code', models.CharField(max_length=6)),
                ('expire_date', models.TimeField()),
            ],
        ),
    ]
