# Generated by Django 3.2.4 on 2021-09-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0003_securitycode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitycode',
            name='expire_date',
        ),
        migrations.AddField(
            model_name='securitycode',
            name='valid_from',
            field=models.DateTimeField(default= '2021-01-05 06:00:00.000000-09:00'),
            preserve_default=False,
        ),
    ]
