# Generated by Django 3.2.4 on 2021-09-06 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0004_auto_20210904_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitycode',
            name='user_id',
        ),
        migrations.AddField(
            model_name='securitycode',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smartMoney_app.sm_user'),
            preserve_default=False,
        ),
    ]
