# Generated by Django 3.2.4 on 2021-09-17 20:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0006_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 20, 20, 54, 448753, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
