# Generated by Django 3.2.4 on 2021-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0011_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'user')},
        ),
    ]
