# Generated by Django 3.2.4 on 2021-09-19 22:33

from django.db import migrations, models
import django.db.models.deletion
import smartMoney_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0012_auto_20210919_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=smartMoney_app.models.Category.other, on_delete=django.db.models.deletion.CASCADE, to='smartMoney_app.category'),
        ),
    ]
