# Generated by Django 3.2.4 on 2021-10-18 15:23

from django.db import migrations, models
import smartMoney_app.base_model


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0014_alter_expense_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(models.Model, smartMoney_app.base_model.baseModel),
        ),
    ]
