# Generated by Django 3.2.4 on 2021-10-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0016_auto_20211018_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='date',
            new_name='month',
        ),
    ]
