# Generated by Django 3.2.4 on 2021-10-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartMoney_app', '0019_alter_budget_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(through='smartMoney_app.Budget_Category', to='smartMoney_app.Category'),
        ),
    ]
